name: podman-compose ausführen

on:
  workflow_dispatch:

env:
  OEREB_SERVER_POSTGRES_DATABASE: vek1
  OEREB_SERVER_POSTGRES_HOST: oereb-server-db
  OEREB_SERVER_POSTGRES_PASSWORD: ${{ secrets.OEREB_SERVER_POSTGRES_PASSWORD }}
  OEREB_SERVER_POSTGRES_PORT: 5432
  OEREB_SERVER_POSTGRES_USER: ${{ secrets.OEREB_SERVER_POSTGRES_USER }}
  OEREB_SERVER_PRINT_SERVICE_HOST: http://oereb-server-print
  OEREB_SERVER_PRINT_SERVICE_PORT: 8080
  OEREB_SERVER_PRINT_SERVICE_PATH: /print/oereb
  OEREB_SERVER_POSTGRES_LOGGER_DATABASE: work
  OEREB_SERVER_POSTGRES_LOGGER_SCHEMA: oereb_server
  OEREB_SERVER_POSTGRES_LOGGER_TABLE: logs
  OEREB_SERVER_INI_LEVEL: development
  OEREB_SERVER_LOG_LEVEL: DEBUG
  OEREB_SERVER_GUNICORN_WORKERS: 4
  OEREB_SERVER_GUNICORN_THREADS: 4
  OEREB_SERVER_GUNICORN_MAX_REQUESTS: 1000
  OEREB_SERVER_DB_GEODB_UA_PASSWORD: ${{ secrets.DUMMY_PW }}
  OEREB_SERVER_DB_OEREB_PASSWORD: ${{ secrets.DUMMY_PW }}
  OEREB_SERVER_DB_TUOEREB_PASSWORD: ${{ secrets.DUMMY_PW }}
  OEREB_SERVER_DB_LOGSCHEMA_URL: ${{ secrets.OEREB_SERVER_DB_LOGSCHEMA_URL }}
  OEREB_SERVER_DB_APPSCHEMA_URL: ${{ secrets.OEREB_SERVER_DB_APPSCHEMA_URL }}
  OEREB_SERVER_DB_TRANSFERSTRUKTUR_URL: ${{ secrets.OEREB_SERVER_DB_TRANSFERSTRUKTUR_URL }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: podman-compose installieren
      run: pip install podman-compose

    - name: Podman da?
      run: podman-compose --help

    - name: podman-compose starten
      run: podman-compose up -d
