name: Docker-Image erstellen

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Versions-Tag"
        required: true
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Podman-Version checken
      run: podman --version

    - name: Image bauen
      run: podman build -t oereb_server:${{ inputs.tag }} .

    - name: Image taggen
      run: podman image tag oereb_server:${{ inputs.tag }} ghcr.io/agibe/oereb_server:${{ inputs.tag }}

    - name: Registry anmelden
      run: echo "${{ secrets.GHCR_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Image pushen
      run: podman image push ghcr.io/agibe/oereb_server:${{ inputs.tag }}
